### ISSUE TITLE
Missing Files: CamelotRouter.sol and ICamelotRouter.sol

### ISSUE THREAD

**Issue by izzetemredemir** [CamelotLabs/core#1]
I've noticed that the CamelotRouter.sol and ICamelotRouter.sol files are missing from the repository. Could you please check and add them if they are intended to be part of the codebase? Thanks!

**Comment by 0xMyrddin** [comment]
Hi, you will find them in the [periphery repository](https://github.com/CamelotLabs/periphery/)

**Comment by izzetemredemir** [comment]
https://github.com/CamelotLabs/periphery/blob/main/contracts/CamelotRouter.sol
